patience_proverbs = [
    "One moment of patience may ward off a great disaster; one moment of impatience may ruin a whole life.",
    "Patience is power; with time and patience, the mulberry leaf becomes a silk gown.",
    "Nature, time and patience are the three great physicians.",
    "Have patience, the grass will be milk soon enough.",
    "Patience is a virtue.",
    "Rice eaten in haste chokes.",
]

go_proverbs = [
    "Don't play 1, 2, 3 - just play 3.",
    "Play slow, win slow; play fast, lose fast.",
    "Lose your first 50 games as quickly as possible.",
    "Your enemy's key point is your own key point.",
    "Urgent points before big points.",
    "Make a fist before striking.",
    "Make territory while attacking.",
    "A rich man should not pick quarrels.",
    "Sacrifice plums for peaches.",
    "Don't go fishing while your house is on fire.",
    "Don't follow proverbs blindly.",
    "The threat is stronger than its execution.",
    "Distant water won't help to put out a fire close at hand.",
    "The fearful suffer a thousand deaths, the brave only one.",
    "Make a feint to the east while attacking in the west.",
    "When in doubt, tenuki (play somewhere else).",
    "People in glass houses shouldn't throw stones.",
    "Beginners play atari (state of a stone or group of stones that has only one liberty).",
    "Lead away a goat in passing.",
    "Those who are good at winning, don't usually fight.",
    "If you cannot succeed, then die gloriously.",
    "Territory really exists only in the end.",
    "In the sound of the stone your can hear its purpose.",
    "If White takes all four corners, Black should resign; if Black takes all four corners, Black should also resign.",
    "Proverbs do not apply to White.",
    "Don't reduce your own liberties.",
]
