language: python

jobs:
  include:
    - &tests        # Anchor https://blog.daemonl.com/2016/02/yaml.html
      stage: Tests
      python: 3.6
      install: pip install -r requirements.txt
      script: pytest --cov=gobot

    # Also test for some other versions
    # <<: is the extend operator = add all fields and extend or modify them afterwards
    # without extend operator only exact copies are possible
    - <<: *tests
      python: 3.5
    - <<: *tests    # Alias for anchor defined above
      python: 3.4
