[tool.ruff]
line-length = 150

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.coverage.html]
directory = "coverage_html_report"

[tool.pyright]
venv = ".venv"
venvPath = "."

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "auto"
filterwarnings = [
  "ignore::DeprecationWarning:botocore.*",
]
addopts = [
  "--cov=gobot",
  "--cov-report=html",
]
