[tool.ruff]
line-length = 150

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.coverage.run]
omit = ["*/settings.py"]

[tool.coverage.html]
directory = "coverage_html_report"

[tool.pytest]
addopts = [
  "--cov=gobot",
  "--cov-report html",
]

[tool.pyright]
venv = ".venv"
venvPath = "."

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "auto"
